# Generated by Django 3.1.1 on 2021-08-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LivroAnuncioImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/anuncios')),
            ],
        ),
        migrations.CreateModel(
            name='LivroAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.JSONField(default=dict, max_length=248)),
                ('categoria', models.CharField(choices=[('V', 'Venda'), ('A', 'Aluguel'), ('T', 'Troca')], max_length=10)),
                ('preco', models.FloatField(blank=True, max_length=64, null=True)),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=64)),
                ('sinopse', models.TextField()),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('imagens', models.ManyToManyField(to='livros.LivroAnuncioImagem')),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='livros.livro')),
            ],
        ),
    ]
