# Generated by Django 3.1.1 on 2021-08-08 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.JSONField(max_length=248)),
                ('categoria', models.CharField(choices=[('V', 'Venda'), ('A', 'Aluguel'), ('T', 'Troca')], max_length=1)),
                ('preco', models.FloatField(max_length=64)),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=64)),
                ('sinopse', models.TextField()),
                ('data_publicacao', models.DateField(blank=True)),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('imagens', models.ManyToManyField(to='livros.LivroVendaImagens')),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='sinopse',
        ),
        migrations.DeleteModel(
            name='LivroVenda',
        ),
        migrations.AddField(
            model_name='livroanuncio',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livros.livro'),
        ),
    ]
