# Generated by Django 3.1.1 on 2021-08-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20210808_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroanuncio',
            name='detalhes',
            field=models.JSONField(blank=True, max_length=248),
        ),
    ]
