# Generated by Django 3.1.1 on 2021-08-09 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_auto_20210808_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LivroVendaImagens',
            new_name='LivroAnuncioImagens',
        ),
        migrations.AlterField(
            model_name='livroanuncio',
            name='livro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='livros.livro'),
        ),
    ]
