# Generated by Django 3.1.1 on 2021-08-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_auto_20210809_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroanuncio',
            name='detalhes',
            field=models.JSONField(default=dict, max_length=248),
        ),
    ]
