# Generated by Django 3.1.1 on 2021-08-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_auto_20210809_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livroanuncio',
            name='data_publicacao',
        ),
    ]
