# Generated by Django 3.1.1 on 2021-08-09 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_remove_livroanuncio_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroanuncio',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='livros.livro'),
        ),
    ]
