# Generated by Django 3.1.1 on 2021-08-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_auto_20210809_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LivroAnuncioImagens',
            new_name='LivroAnuncioImagem',
        ),
    ]
