# Generated by Django 3.1.1 on 2021-08-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_auto_20210810_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroanuncio',
            name='preco',
            field=models.FloatField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='livroanuncioimagem',
            name='imagem',
            field=models.ImageField(upload_to='images/anuncios'),
        ),
    ]
