# Generated by Django 3.1.1 on 2021-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_auto_20210811_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroanuncio',
            name='categoria',
            field=models.CharField(choices=[('V', 'Venda'), ('A', 'Aluguel'), ('T', 'Troca')], max_length=10),
        ),
    ]
