# Generated by Django 3.1.1 on 2021-08-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_auto_20210811_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroanuncio',
            name='preco',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
    ]
