# Generated by Django 3.1.1 on 2021-08-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favoritos',
            field=models.ManyToManyField(to='livros.LivroAnuncio'),
        ),
    ]
